### ISSUE TITLE
[Feature Request] SRS only contains the PowerCLI modules

### ISSUE THREAD

**Issue by lucdekens** [vmware/script-runtime-service-for-vsphere#19]
In the current build the SRS only seems to contain the PowerCLI modules.
Can the build have an option to also include the standard PS modules, that come with PS, in the container?

This would probably also allow users to install additional modules in SRS.
Currently that option is not there.

**Comment by dmilov** [comment]
The way to package other modules is to specify a directory with the desired modules on `./build.sh <PowerCLI Modules path>`. This build packages this folder in the runspace container and mounts is on PSModulePath environment variable. PowerCLI is required to be there because service calls Connect-VIService internally. You can prepare folder with PowerCLI modules and other modules of choice and build the OVA with those. This way you'll get runspace with custom modules.

Official product will be bundled with PowerCLI only and in future version we'll add the possibility to mount custom modules/scripts from external source.
