### ISSUE TITLE
Build fails for ESXi 6.7+ (VNC)

### ISSUE THREAD

**Issue by lucdekens** [vmware/script-runtime-service-for-vsphere#4]
Seems the build relies on VNC being available on the ESXi node.
And since ESXi 6.7, the VNC service was removed.

Using **vnc_over_websocket** fixes that, but creates a dependency on the packer version.

**Comment by dmilov** [comment]
Packer related issues
https://github.com/hashicorp/packer/issues/6482
https://github.com/hashicorp/packer/issues/8984

TODOs: 
1. Explore **vsphere-iso** for ESXi7.0 
2. Update build with **vnc_over_websocket** for ESXi 6.7
3. Parametrize `build.sh` with target ESXi/VC for build and deploy and remove hard-coded values in photon.json and photon-builder.json

**Comment by lamw** [comment]
FYI - VNC was actually removed in 7.0, hence the issue I had filed hashicorp/packer#8984

For the VEBA project, we continue to use `vmware-iso` provider since there were some issues when I had looked at the vsphere-iso provier and there isn't clean transition between the two. Having relatively new Packer version isn't a bad thing either, especially with fixes/enhancements. I know the SRS project based its appliance build process from VEBA, so I know you can easily update w/changes below and not have to worry about specific ESXi/VC versions.

You can ensure the Packer client is running minimal version that supports VNC over websockets, you can add the following (which we do and 1.6.3 is the minimal version)

```
"min_packer_version": "1.6.3"
```

As noted already `vnc_over_websocket` param is needed but we also default to adding `insecure_connection` since most users have self-signed TLS certificate.
```
"vnc_over_websocket": true,
"insecure_connection": true,
```
